import os
basedir = os.path.abspath(os.path.dirname(__file__))

DEBUG = False
TESTING = False
CSRF_ENABLED = True

SQLALCHEMY_DATABASE_URI = os.environ['DATABASE_URL']
SQLALCHEMY_TRACK_MODIFICATIONS = False

SECRET_KEY = os.environ['SECRET_KEY']
WTF_CSRF_SECRET_KEY = os.environ['WTF_CSRF_SECRET_KEY']

RECAPTCHA_ENABLED = True
RECAPTCHA_SITE_KEY = os.environ['CAPTCHA_PUBLIC_KEY']
RECAPTCHA_SECRET_KEY = os.environ['CAPTCHA_PRIVATE_KEY']
RECAPTCHA_THEME = "light"
