"""empty message

Revision ID: 1f117af36976
Revises: 324966e05118
Create Date: 2020-09-06 01:42:46.824271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f117af36976'
down_revision = '324966e05118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('raiseUser', sa.Integer(), nullable=True),
    sa.Column('raiseDate', sa.Date(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('assignUser', sa.Integer(), nullable=True),
    sa.Column('open', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Users', sa.Column('enabled', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'Users', ['email'])
    op.create_unique_constraint(None, 'Users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_constraint(None, 'Users', type_='unique')
    op.drop_column('Users', 'enabled')
    op.drop_table('Reports')
    # ### end Alembic commands ###
