"""empty message

Revision ID: a17a7d4fd61d
Revises: b294c791120b
Create Date: 2021-01-24 17:46:05.710426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17a7d4fd61d'
down_revision = 'b294c791120b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('data', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('name', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('switch', sa.Integer(), nullable=True))
    op.drop_column('settings', 'value')
    op.drop_column('settings', 'setting')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('setting', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('settings', sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('settings', 'switch')
    op.drop_column('settings', 'name')
    op.drop_column('settings', 'data')
    # ### end Alembic commands ###
