"""empty message

Revision ID: d11144b6f8a5
Revises: e9422d368976
Create Date: 2020-09-13 19:36:46.105018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd11144b6f8a5'
down_revision = 'e9422d368976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('notes', sa.String(), nullable=True))
    op.add_column('tickets', sa.Column('resolution', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'resolution')
    op.drop_column('tickets', 'notes')
    # ### end Alembic commands ###
